### PR TITLE
fix: added correct link on the footer section

### PR DESCRIPTION
**Pull request by SubhamB2003**
### Related Issue 

Closes: #843 

#### Changes made 👷🏻‍♂️
I changed only the wrong URL in the footer section previously it was "/display/events" and "/shops/shop" You also see the below screenshot. The correct URL is "/events" and "/shop".

#### Screenshots  📸
before
image

after
image
image

### CODE REVIEW

**Comment by SubhamB2003** [comment]
Hey, I really sorry for creating a new pr instead of updating the previous one. Actually, I am not able to resolve the conflicts that's why I created a new one.

**Comment by tamalCodes** [comment]
Cool. Please create the PR from the `Beta` branch, and pull changes from there, rather than from the `main` branch as i marked your previous PR as https://github.com/tamalCodes/Milan/labels/Beta%20Release too.

**Comment by SubhamB2003** [comment]
> Cool. Please create the PR from the `Beta` branch, and pull changes from there, rather than from the `main` branch as i marked your previous PR as [ Beta Release](https://github.com/tamalCodes/Milan/labels/Beta%20Release) The changes in the Issue/PR are in beta stage, and might be unstable in production. too.

Hey, can you please tell me how can I pull the beta branch changes?

**Comment by tamalCodes** [comment]
Well then do one thing close this PR. Remember the changes you have done. 
Now if you have just forked the `main` branch, delete the forked version. And fork again.

Remember to uncheck this option. Copy all the branches.
image

Then once you are in your local, you can checkout the `beta` branch and work on then there and then raise a PR from your forked version to our `beta` branch.

This is not the case everytime. In 90% of the cases the `beta` and the `main` branches are almost similar so it doesnot matter if you forked just the main branch, in our case we just made like 100+ changes so it's a hassle for the devs like you to unfork and re-fork again. Sorry for the trouble.

**Pull request closed without merging**
