### PR TITLE
fix(ClubsPage): improve cards on club page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
### Related Issue 

Closes: #
Closes : #721 

#### Changes made 👷🏻‍♂️
Added a box shadow to the cards on the club page, increased the width of the cards and decreased the height of the cards by a few pixels to make it look more prominent and slightly increased the size of the view button to make it look more prominent on the card and made cursor pointer when hovering the card along with a consistent box shadow.

#### Screenshots  📸
Before
Screenshot 2023-06-13 at 2 49 24 PM

After

Screenshot 2023-06-13 at 2 14 23 PM

Screenshot 2023-06-13 at 2 14 35 PM

### CODE REVIEW

**Review by tamalCodes — CHANGES_REQUESTED** [review]
The cards are looking way too wide, please revert back any changes that are changing the width of the card, and only keep the `hover` functionality to it.

image

**Comment by karthiknadar1204** [comment]
@tamalCodes Will do and push the changes today itself
Thank you

**Comment by karthiknadar1204** [comment]
@tamalCodes Please close this pr for now, I am opening a new pr as when I pulled the changes onto my branch, it showed a bunch of issues, have added the changes again, submitting pr in a bit.
Thank you

**Comment by tamalCodes** [comment]
> @tamalCodes Please close this pr for now, I am opening a new pr as when I pulled the changes onto my branch, it showed a bunch of issues, have added the changes again, submitting pr in a bit. Thank you

Sure.

**Pull request closed without merging**
