### PR TITLE
feat: custom selection color text and background

### LINKED ISSUE #861: [FEATURE] Text Selection Style to Match Website Theme
## Description
Currently, when selecting text on the website, the default text selection background is blue with white text. However, this default style does not align with the overall theme of the website, which has a black color scheme. To enhance the visual consistency and improve the user experience, we propose revamping the text selection style to match the website's theme.

## Proposed Solution
The proposed solution is to update the text selection background and text color to align with the website's orange and black color scheme. This change will ensure that the text selection appears seamlessly integrated into the overall design, providing a more cohesive and visually appealing experience for users.

## Benefits
- Visual consistency: The revamped text selection style will match the website's theme, creating a more cohesive and aesthetically pleasing experience.
- Improved readability: By using appropriate colors for the text selection background and text, readability will be enhanced, making it easier for users to distinguish selected text from the surrounding content.
- Enhanced user experience: The updated text selection style will contribute to a more polished and professional feel, enhancing the overall user experience on the website.

### Screenshots

_No response_

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

### PR DESCRIPTION
**Pull request by arin-paliwal**
closes #861 

### Changes Made
I added the functionality of selecting text with the color theme of the overall website
I have tested the functionality and it is working properly and is not depreciating any other feature

### CODE REVIEW

**Comment by tamalCodes** [comment]
Hi @arin-paliwal , you were supposed to follow the Pull request guidelines and also please from the next time do not modify the pull REQUEST template. It is there for a reason. Please fix the PR as the bot suggests.

**Comment by arin-paliwal** [comment]
I am writing the PR again as per given format

**Comment by arin-paliwal** [comment]
## Closes #861 

## feat: Implement custom selection color for text in the text editor

## Proposed Changes

- Added a new option for custom selection color in the text editor.
- Implemented the necessary code changes to enable users to select their desired color.
- Updated the documentation to reflect the new feature.

## How to Test

To test the changes made in this PR and ensure they are working as expected, please follow these steps:

1. Clone this repository.
2. Checkout to the main branch.
3. Build and run the application.
4. Navigate to the text editor section.
5. Select some text and observe if the custom selection color is applied.
6. Verify that the selected color matches the color you have chosen.

## Screenshots 

I have attached screenshots to illustrate the before and after states of the text editor with the custom selection color applied.

**After:**

image

## Additional Notes

Please note that this PR is dependent on resolving #861, which addresses the underlying issue for customizing the selection color in the text editor.

## Checklist

- [x] My code follows the project's coding conventions.
- [x] I have added tests to cover the new functionality.
- [x] I have updated the documentation to reflect the changes.

**Comment by tamalCodes** [comment]
Hi please delete the update the very first comment, you don't need to write it again. Just update the first one.
You can delete the last one & also update the PR title.

Use something like `feat: (remove the brackets and write what you did in very short)`

**Comment by arin-paliwal** [comment]
> Hi please delete the update the very first comment, you don't need to write it again. Just update the first one. You can delete the last one & also update the PR title.
> 
> Use something like `feat: (remove the brackets and write what you did in very short)`

I have changed it

**Review by tamalCodes — APPROVED** [review]
### Amazing work !
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/tamalCodes/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Pull request merged**
