### PR TITLE
feat: scroll to top button

### PR DESCRIPTION
**Pull request by karthiknadar1204**
### Related Issue 

Closes: #908 

#### Changes made 👷🏻‍♂️
Added a scroll to top button on all the pages

#### Screenshots  📸
https://www.awesomescreenshot.com/video/19278642?key=18bfa8d3804b0f3962d7a92b95f4da70

### CODE REVIEW

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Hi there, there are a couple of changes that I would need you to do:

 - In the components folder, we already have a folder called `/Button`, inside that you can make another folder called `/BacktoTop`.
- Rename the files from `GoToTop.jsx` to `BacktoTop.jsx` and `BacktoTop.css` and put both of those files inside the `/BacktoTop` folder.

Next, we would talk about the design, 

 - The button looks huge (take a look at the SS below), we need it to be the same way we have 2 of our buttons. Do take a look at the video below for a proper explanation. Make sure you have the sound turned on (1.25x is better)


https://github.com/tamalCodes/Milan/assets/72851613/5bccbd15-5b2a-4d86-9856-4bed12aec00b

**Comment by karthiknadar1204** [comment]
Thank you for the review @tamalCodes ,Will get it done

**Comment by karthiknadar1204** [comment]
@tamalCodes Will push the changes soon, have my exams going on so on a tight schedule, will wrap up by this weekend.
Thank you

**Comment by tamalCodes** [comment]
> @tamalCodes Will push the changes soon, have my exams going on so on a tight schedule, will wrap up by this weekend. Thank you

No worries. Take your time.

**Comment by karthiknadar1204** [comment]
Have resumed the work

**Comment by karthiknadar1204** [comment]
Have done all the requested changes, pushing the changes

**Comment by karthiknadar1204** [comment]
https://www.awesomescreenshot.com/video/19520861?key=537e2317b169eac559e3c472e83ad8ec

**Review by tamalCodes — APPROVED** [review]
### Amazing work !
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/tamalCodes/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Pull request merged**
