### PR TITLE
fix: club login and registration page with validation errors and changes requested done

### LINKED ISSUE #735: [BUG] Login and Register Form validations and error messages
### Description
Although the api response messages and notificaions are totally proper but,

Login and Register Forms can be imporve very much by adding validation messages and error messages at right places.
First i will add Global components for Forms, inputs and submit with onChange functionality which will help to improve the accessability and productivity of code.

After that i will add form validation by which proper error message will show on fields.

please assign me this issue to fix under GSSOC'23

### Screenshots

Screenshot from 2023-05-23 16-07-10
Screenshot from 2023-05-23 16-06-53

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

### PR DESCRIPTION
**Pull request by Pushpendra33**
### Related Issue 
closes #735 

Closes: #

#### Changes made 👷🏻‍♂️
Improved club login and register form with global components and validation schema (yup).
With this update, users can access the application using their credentials, providing an additional layer of error throwing on the login and registration process for clubs.
With react-hook-form users have to pass all the validations to perform sign-up or login.

Packages installed by my side
`@hookform/resolvers`
`react-hook-form`
`yup`

Just so you know – all the changes requested from your side are completed.

#### Screenshots  📸

Screenshot from 2023-06-14 15-41-13

### CODE REVIEW

**Comment by tamalCodes** [comment]
Hi @Pushpendra33 , what should i do with #823 ? 
Is it to be closed ?

**Comment by Pushpendra33** [comment]
> Hi @Pushpendra33 , what should i do with #823 ? Is it to be closed ?
> 
> There's no point in having 2 separate PRs.

please close #823 
@tamalCodes  , due to some issue in my main branch, i have to commit from another branch.
so merge this latest PR and close all other one.
Also close the issue.

**Comment by tamalCodes** [comment]
Thanks for the info, i saw that you have added 3 different packages, can you explain what are the needs of those ? 
Because adding a lot of packages might have different side effects - so I really wanna understand the necessity.

**Comment by Pushpendra33** [comment]
> Thanks for the info, i saw that you have added 3 different packages, can you explain what are the needs of those ? Because adding a lot of packages might have different side effects - so I really wanna understand the necessity.

of course @tamalCodes 
For adding custom validations and error messages i have used these 3 packages which help by adding proper validation with a single schema for a particular form.

1. Yup : Yup is a schema builder for runtime value parsing and validation. Define a schema, transform a value to match, assert the shape of an existing value, or both. Yup schema are extremely expressive and allow modeling complex, interdependent validations, or value transformation.

2. React-hook-form : Performant, flexible and extensible forms with easy-to-use validation. For applying our validation we have to use this package as it will first validate the whole form and after checking all errors and validations then it will submit form.

3. @hookform/resolvers : This package allows you to use any external validation library such as Yup, Joi and many others. The goal is to make sure you can seamlessly integrate whichever validation library you prefer. If you're not using a library, you can always write your own logic to validate your forms.

**Comment by Pushpendra33** [comment]
Have you merged the code or not? @tamalCodes

**Comment by Pushpendra33** [comment]
What is the status @tamalCodes ??
why are you not merging my code as new contributors are also working on the same thing which i have done already.

**Comment by tamalCodes** [comment]
Hi @Pushpendra33 , 

 - There are conflicting files that you need to resolve very carefully. Without that merging is not possible.
 - There are no other contributors lined up in this issue, if there would be, I'll handle them do not worry.
 - The nature of this PR makes me think about the chances of merging it. I was playing around with the authentication and I realized that all this work can be done without having to use 3rd-party libraries like `@hookform/resolvers, react-hook-form, yup`. Take a look at [THIS](https://github.com/tamalCodes/Milan/pull/892) PR, where I used custom Hooks to validate a form.

- Now the thing is as I told you earlier, the libraries depend on the project - if we would have huge forms, which has N number of fields - then putting together such libraries would be the BEST case scenario. But in our case, we have very few fields that to a lot of them do not even needs different validations other than `minLength`.

- Also learn to be patient when you are contributing to Opensource. It's an important key for both the maintainers and OSS contributors. I wait up to a month before closing any inactive issue/PR - and in this case, I think you can /should wait at least 3 weeks for the same. Given the size of the files changed - I need to make sure that there are no dependencies that might break stuff.
- In the issue you raised #735 there were no such libraries mentioned so I did not expect such a `major` change was not expected. 

Anyways I will do take a look at the code, suggest changes, and review it overall.
Thanks.

**Pull request closed without merging**
