### PR TITLE
docs: update checklist in all issue forms

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
### Related Issue 

Closes: #960

#### Changes made 👷🏻‍♂️

Updated checklist:

- add a non-mandatory field: `I am a GSSoC23 contributor`
- add link to check similar issue

#### Screenshots  📸

> Image
image

### CODE REVIEW

**Comment by tamalCodes** [comment]
Hi @Anmol-Baranwal , please enable issues on the [fork version](https://github.com/Anmol-Baranwal/Milan/tree/hack_issue_forms), this helps me interact and cross check for the same !

**Comment by Anmol-Baranwal** [comment]
> Hi @Anmol-Baranwal , please enable issues on the [fork version](https://github.com/Anmol-Baranwal/Milan/tree/hack_issue_forms), this helps me interact and cross check for the same !

Sure, give me 10 minutes as I am away from the Laptop.

**Comment by Anmol-Baranwal** [comment]
> Hi @Anmol-Baranwal , please enable issues on the [fork version](https://github.com/Anmol-Baranwal/Milan/tree/hack_issue_forms), this helps me interact and cross check for the same !

I have enabled it, but it won't be visible because it is not on the main branch.

These are the basic ones, and since there are no errors, they will work as intended.

**Comment by Anmol-Baranwal** [comment]
What is the status? Is there any problem.

**Review by tamalCodes — APPROVED** [review]
### Amazing work !
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/tamalCodes/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Pull request merged**
