### PR TITLE
feat: added hover state on navbar

### PR DESCRIPTION
**Pull request by Souravvmishra**
### Related Issue 

Closes:  #734

#### Changes made 👷🏻‍♂️

Added hover state on the link items in the navbar.

### CODE REVIEW

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Hi there, do add a transition so that the animation of hovering in and hovering out is smooth. Currently, it feels pretty bad to Hover.

**Comment by Souravvmishra** [comment]
@tamalCodes I have added the required transition. PLease Check

**Review by tamalCodes — APPROVED** [review]
### Amazing work !
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/tamalCodes/Milan/releases) (we will tag you and mention your work) and also [shoutouts ](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

**Comment by Souravvmishra** [comment]
This PR has not been considered in the gssoc2023. Can someone Check & let me know where I went wrong.

**Comment by tamalCodes** [comment]
> This PR has not been considered in the gssoc2023. Can someone Check & let me know where I went wrong.

Hi, we are looking into it - please wait !

**Pull request merged**
