### PR TITLE
feat: added the animation to the website with framer motion

### PR DESCRIPTION
**Pull request by ManishaSwain8**
style: added the animation to the website with framer motion
### Related Issue 
Closes: #764 
#### Changes made 👷🏻‍♂️under GSSOC 2023
1. Added animation to whole website using Framer motion replacing AOS.  (and the animation is set for once , not repeated every time person scrolls ,if any changes req. do inform)  : )

### CODE REVIEW

**Comment by tamalCodes** [comment]
Thanks for the PR, I will review it soon ⚡

**Comment by tamalCodes** [comment]
Hi @ManishaSwain8 , do take a look at this [video](https://www.loom.com/share/db9a41e4a1054c088b1007f6362e13c8) , make sure your volume is up!

Love your work ⚡

**Comment by ManishaSwain8** [comment]
Afternoon @tamalCodes ,
I went through your video but I didn't get the vanishing part,

https://github.com/tamalCodes/Milan/assets/96622693/a22b6bfb-afa6-4fac-bda1-b61629371df2

You want like this ? ? ?

**Comment by tamalCodes** [comment]
That makes sense, sorry I should have been clear, can you please watch [this](https://www.loom.com/share/30bca242209a4bf8aae96755f18df052) video - I think that will clear out any confusion that exists.

**Comment by ManishaSwain8** [comment]
@tamalCodes got it !
I will work on it , and for the extra image that I added, img was there in the code as you said for mobile view sorry about that I didn't put much attention to the code .
And the rest changes will be done  !

**Comment by ManishaSwain8** [comment]
Afternoon,@tamalCodes 
I did all the changes as per the requirement but I am not able to find the solution for the reverse animation in Framer Motion,
I went through the whole, documentation but did not find any useful article related to the issue .Though I know (reverse in transition property )but I have no idea how to trigger it while scroll.
Hope you understand ,You can assign this issue to someone else !  : |)

**Comment by tamalCodes** [comment]
> Afternoon,@tamalCodes I did all the changes as per the requirement but I am not able to find the solution for the reverse animation in Framer Motion, I went through the whole, documentation but did not find any useful article related to the issue .Though I know (reverse in transition property )but I have no idea how to trigger it while scroll. Hope you understand ,You can assign this issue to someone else ! : |)

Intresting, well in that case I think we should keep `aos` as it is and not implement these changes. 
Thanks for your time, it means a lot when someone spends time brainstorming ⚡

**Comment by ManishaSwain8** [comment]
Yup , sorry for inconvenience but I will keep on hunting for the solution specially in *Framer Motion * ! : |)

**Pull request closed without merging**
