### PR TITLE
fix: error page overflow issue

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
### Related Issue #905 

Closes: #905  

#### Changes made 👷🏻‍♂️
Hello @NikhilRaikwar ,
I have fixed the overflow issue in the error page and now it's aligned properly.

#### Screenshots  📸

Screenshot from 2023-06-28 20-44-21

### CODE REVIEW

**Comment by NikhilRaikwar** [comment]
Hey @SyedImtiyaz-1 I'm not an assigner @tamalCodes Sir is assigner and mentor of the project.

**Comment by tamalCodes** [comment]
Hi @SyedImtiyaz-1 , 
 - please donot include " `` " inside the PR title itself
 - Please fix the PR title to being a proper one

**Comment by SyedImtiyaz-1** [comment]
@tamalCodes Title fixed. It's ready to merge

**Comment by tamalCodes** [comment]
> @tamalCodes Title fixed. It's ready to merge

This is what happens when you do not follow the instructions at all before making a PR.
Please fix the title accordingly, we keep it as [conventional](https://www.conventionalcommits.org/en/v1.0.0/) as possible.
image

**Comment by SyedImtiyaz-1** [comment]
@tamalCodes .

**Comment by SyedImtiyaz-1** [comment]
@tamalCodes ,
please merge it.

**Pull request merged**
